//Palidroma
//Chiedere all'utente di inserire una parola
//VEDERE SE LA PAROLA INSERITA DALL'UTENTE E' PALINDROMA
//SCOMPORRE LA PAROLA
//INVERTIRE LE LETTERE
//RINCOMPORRE LA PAROLA
//SE E' PALINDROMA DICHIARARE CHE QUESTA PAROLA E' PALINDROMA
// ALTRIMENTI NON E' PALINDROMA
