//Palidroma
//Chiedere all'utente di inserire una parola
//VEDERE SE LA PAROLA INSERITA DALL'UTENTE E' PALINDROMA
//SE E' PALINDROMA DICHIARARE CHE QUESTA PAROLA E' PALINDROMA
// ALTRIMENTI NON E' PALINDROMA
